Repository NOW-SOPT-APP9-SPOTIFY/Spotify_iOS, pull requests merged in 2024-05, with the labels that each got.

#2 [Setting] #1 - 프로젝트 초기 세팅
  Spotify-iOS/Spotify-iOS.xcodeproj/project.pbxproj
  Spotify-iOS/Spotify-iOS.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Spotify-iOS/Spotify-iOS.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Spotify-iOS/Spotify-iOS.xcworkspace/contents.xcworkspacedata
  Spotify-iOS/Spotify-iOS.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Spotify-iOS/Spotify-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Spotify-iOS/Spotify-iOS/Application/AppDelegate.swift
  Spotify-iOS/Spotify-iOS/Application/Base.lproj/LaunchScreen.storyboard
  Spotify-iOS/Spotify-iOS/Application/Info.plist
  Spotify-iOS/Spotify-iOS/Application/SceneDelegate.swift
  Spotify-iOS/Spotify-iOS/Application/ViewController.swift
  Spotify-iOS/Spotify-iOS/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  Spotify-iOS/Spotify-iOS/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Spotify-iOS/Spotify-iOS/Resource/Assets.xcassets/Contents.json
  Spotify-iOS/Spotify-iOS/TabBar/SpotifyTabBarController.swift
  Spotify-iOS/Spotify-iOS/TabBar/SpotifyTabBarItem.swift
Labels: 명진, Setting

#5 [Setting] #4 - Color Asset 추가
  Spotify-iOS/Spotify-iOS/Global/Resource/Assets.xcassets/spotifyBg.colorset/Contents.json
  Spotify-iOS/Spotify-iOS/Global/Resource/Assets.xcassets/spotifyBlack.colorset/Contents.json
  Spotify-iOS/Spotify-iOS/Global/Resource/Assets.xcassets/spotifyBlue10.colorset/Contents.json
  Spotify-iOS/Spotify-iOS/Global/Resource/Assets.xcassets/spotifyBlue20.colorset/Contents.json
  Spotify-iOS/Spotify-iOS/Global/Resource/Assets.xcassets/spotifyGray10.colorset/Contents.json
  Spotify-iOS/Spotify-iOS/Global/Resource/Assets.xcassets/spotifyGray20.colorset/Contents.json
  Spotify-iOS/Spotify-iOS/Global/Resource/Assets.xcassets/spotifyGray30.colorset/Contents.json
  Spotify-iOS/Spotify-iOS/Global/Resource/Assets.xcassets/spotifyGray40.colorset/Contents.json
  Spotify-iOS/Spotify-iOS/Global/Resource/Assets.xcassets/spotifyGreen.colorset/Contents.json
  Spotify-iOS/Spotify-iOS/Global/Resource/Assets.xcassets/spotifyLime.colorset/Contents.json
  Spotify-iOS/Spotify-iOS/Global/Resource/Assets.xcassets/spotifyPink.colorset/Contents.json
  Spotify-iOS/Spotify-iOS/Global/Resource/Assets.xcassets/spotifyPupple.colorset/Contents.json
  Spotify-iOS/Spotify-iOS/Global/Resource/Assets.xcassets/spotifyRed.colorset/Contents.json
Labels: 민성, Setting

#7 [Setting] #6 - 프로젝트에 필요한 기본 세팅
  Spotify-iOS/Spotify-iOS.xcodeproj/project.pbxproj
  Spotify-iOS/Spotify-iOS/Application/Info.plist
  Spotify-iOS/Spotify-iOS/Global/Resource/Extension/UIView+.swift
  Spotify-iOS/Spotify-iOS/Global/Resource/Extension/getClassName.swift
  Spotify-iOS/Spotify-iOS/Network/Base/Config.swift
  Spotify-iOS/Spotify-iOS/Presentation/Home/HomeView.swift
  Spotify-iOS/Spotify-iOS/Presentation/Home/HomeViewController.swift
Labels: 명진, Setting

#11 [Chore] #10 - 폴더링 구조 변경
  Spotify-iOS/Spotify-iOS.xcodeproj/project.pbxproj
  Spotify-iOS/Spotify-iOS/Global/Extension/UIView+.swift
  Spotify-iOS/Spotify-iOS/Global/Extension/getClassName.swift
  Spotify-iOS/Spotify-iOS/Global/Resource/Assets.xcassets/Icon/ic_back_gray.imageset/Contents.json
  Spotify-iOS/Spotify-iOS/Global/Resource/Assets.xcassets/Icon/ic_back_gray.imageset/ic_back_gray.svg
  Spotify-iOS/Spotify-iOS/Global/Resource/Assets.xcassets/Icon/ic_back_white.imageset/Contents.json
  Spotify-iOS/Spotify-iOS/Global/Resource/Assets.xcassets/Icon/ic_back_white.imageset/ic_back_white.svg
  Spotify-iOS/Spotify-iOS/Global/Resource/Assets.xcassets/Icon/ic_next_gray.imageset/Contents.json
  Spotify-iOS/Spotify-iOS/Global/Resource/Assets.xcassets/Icon/ic_next_gray.imageset/ic_next_gray.svg
  Spotify-iOS/Spotify-iOS/Global/Resource/Assets.xcassets/Icon/ic_next_white.imageset/Contents.json
  Spotify-iOS/Spotify-iOS/Global/Resource/Assets.xcassets/Icon/ic_next_white.imageset/ic_chevron_forward.svg
  Spotify-iOS/Spotify-iOS/Presentation/ViewControllers/Artist/ArtistViewController.swift
  Spotify-iOS/Spotify-iOS/Presentation/ViewControllers/Home/HomeViewController.swift
  Spotify-iOS/Spotify-iOS/Presentation/Views/Artist/ArtistView.swift
  Spotify-iOS/Spotify-iOS/Presentation/Views/Home/HomeView.swift
Labels: 나연, Chore

#13 [Design] #12 - 기본 레이아웃 구현을 위한 설정 작업
  Spotify-iOS/Spotify-iOS.xcodeproj/project.pbxproj
  Spotify-iOS/Spotify-iOS/Presentation/Cells/MusicItemCollectionViewCell.swift
  Spotify-iOS/Spotify-iOS/Presentation/ViewControllers/Recommand/MusicRecommendViewController.swift
  Spotify-iOS/Spotify-iOS/Presentation/Views/Recommand/MusicRecommendView.swift
Labels: 민성, Design

#16 [Setting] #15 - swiftLint 설치 하였습니다.
  Spotify-iOS/.swiftlint.yml
  Spotify-iOS/Spotify-iOS.xcodeproj/project.pbxproj
  Spotify-iOS/Spotify-iOS/Application/ViewController.swift
  Spotify-iOS/Spotify-iOS/Global/Extension/UIView+.swift
  Spotify-iOS/Spotify-iOS/Network/Base/Config.swift
  Spotify-iOS/Spotify-iOS/Presentation/ViewControllers/Artist/ArtistViewController.swift
  Spotify-iOS/Spotify-iOS/Presentation/ViewControllers/Recommand/MusicRecommendViewController.swift
  Spotify-iOS/Spotify-iOS/Presentation/Views/Home/HomeView.swift
  Spotify-iOS/Spotify-iOS/Presentation/Views/Recommand/MusicRecommendView.swift
Labels: 명진, Setting, Fix ⚡️

#18 [Feat] #10 - 아티스트 페이지(뷰4) 기본 레이아웃 UI 구현
  Spotify-iOS/Spotify-iOS.xcodeproj/project.pbxproj
  Spotify-iOS/Spotify-iOS/Data/TabbarModel.swift
  Spotify-iOS/Spotify-iOS/Global/Extension/String+.swift
  Spotify-iOS/Spotify-iOS/Global/Extension/UIView+.swift
  Spotify-iOS/Spotify-iOS/Global/Resource/Assets.xcassets/Image/img_bruno_mars.imageset/Contents.json
  Spotify-iOS/Spotify-iOS/Global/Resource/Assets.xcassets/Image/img_bruno_mars.imageset/img_bruno_mars.svg
  Spotify-iOS/Spotify-iOS/Presentation/Cells/ArtistTabbarCell.swift
  Spotify-iOS/Spotify-iOS/Presentation/Common/RoundBorderCustomButton.swift
  Spotify-iOS/Spotify-iOS/Presentation/ViewControllers/Artist/ArtistMusicViewController.swift
  Spotify-iOS/Spotify-iOS/Presentation/ViewControllers/Artist/ArtistViewController.swift
  Spotify-iOS/Spotify-iOS/Presentation/Views/Artist/ArtistHeaderView.swift
  Spotify-iOS/Spotify-iOS/Presentation/Views/Artist/ArtistMusicView.swift
  Spotify-iOS/Spotify-iOS/Presentation/Views/Artist/ArtistView.swift
Labels: 나연, Feat 🍀, Design

#21 [Fix] progress bar 화면에 안 뜨는 문제 해결
  Spotify-iOS/Spotify-iOS/Presentation/Cells/MusicItemCollectionViewCell.swift
  Spotify-iOS/Spotify-iOS/Presentation/Views/Recommend/MusicProgressBarView.swift
  Spotify-iOS/Spotify-iOS/Presentation/Views/Recommend/MusicRecommendView.swift
Labels: 민성, Fix ⚡️

#31 [Feat] #29 - 두번째 Recommned 뷰와 Blur 뷰를 연결 합니다.
  Spotify-iOS/Spotify-iOS.xcodeproj/project.pbxproj
  Spotify-iOS/Spotify-iOS/Data/ArtistTabbarModel.swift
  Spotify-iOS/Spotify-iOS/Data/Dto.swift
  Spotify-iOS/Spotify-iOS/Data/RecommendDTO.swift
  Spotify-iOS/Spotify-iOS/Network/Network.swift
  Spotify-iOS/Spotify-iOS/Network/Service/SpotifyService.swift
  Spotify-iOS/Spotify-iOS/Presentation/Common/RoundBorderCustomButton.swift
  Spotify-iOS/Spotify-iOS/Presentation/TabBar/SpotifyTabBarController.swift
  Spotify-iOS/Spotify-iOS/Presentation/TabBar/SpotifyTabBarItem.swift
  Spotify-iOS/Spotify-iOS/Presentation/ViewControllers/Blur/BlurViewController.swift
  Spotify-iOS/Spotify-iOS/Presentation/ViewControllers/Home/CardViewController.swift
  Spotify-iOS/Spotify-iOS/Presentation/ViewControllers/Recommand/MusicRecommendViewController.swift
  Spotify-iOS/Spotify-iOS/Presentation/Views/Artist/ArtistMusicView.swift
  Spotify-iOS/Spotify-iOS/Presentation/Views/Blur/BlurView.swift
Labels: 명진, Feat 🍀

#32 [Feat] #26 - 아티스트 페이지 상세 조회, 인기 차트 조회 API 연결
  Spotify-iOS/Spotify-iOS.xcodeproj/project.pbxproj
  Spotify-iOS/Spotify-iOS/Data/ArtistDTO.swift
  Spotify-iOS/Spotify-iOS/Data/ArtistImageModel.swift
  Spotify-iOS/Spotify-iOS/Data/ArtistPopularMusicModel.swift
  Spotify-iOS/Spotify-iOS/Global/Resource/Assets.xcassets/Image/img_album_24kMagic.imageset/Contents.json
  Spotify-iOS/Spotify-iOS/Global/Resource/Assets.xcassets/Image/img_album_24kMagic.imageset/img_album_24kMagic.jpeg
  Spotify-iOS/Spotify-iOS/Global/Resource/Assets.xcassets/Image/img_album_doo-wops.imageset/Contents.json
  Spotify-iOS/Spotify-iOS/Global/Resource/Assets.xcassets/Image/img_album_doo-wops.imageset/img_album_doo-wops.jpeg
  Spotify-iOS/Spotify-iOS/Global/Resource/Assets.xcassets/Image/img_album_silkSonic.imageset/Contents.json
  Spotify-iOS/Spotify-iOS/Global/Resource/Assets.xcassets/Image/img_album_silkSonic.imageset/img_album_silkSonic.jpeg
  Spotify-iOS/Spotify-iOS/Global/Resource/Assets.xcassets/Image/img_album_unorthodoxJukebox.imageset/Contents.json
  Spotify-iOS/Spotify-iOS/Global/Resource/Assets.xcassets/Image/img_album_unorthodoxJukebox.imageset/img_album_example.png
  Spotify-iOS/Spotify-iOS/Network/Service/SpotifyService.swift
  Spotify-iOS/Spotify-iOS/Network/ServiceType/ArtistServiceType.swift
  Spotify-iOS/Spotify-iOS/Presentation/Cells/Artist/ArtistMusicFooterReusableView.swift
  Spotify-iOS/Spotify-iOS/Presentation/Cells/Artist/ArtistMusicHeaderReusableView.swift
  Spotify-iOS/Spotify-iOS/Presentation/Cells/Artist/ArtistRecommendationCollectionViewCell.swift
  Spotify-iOS/Spotify-iOS/Presentation/Cells/Artist/ArtistTabbarCell.swift
  Spotify-iOS/Spotify-iOS/Presentation/Cells/Artist/PopularMusicCollectionViewCell.swift
  Spotify-iOS/Spotify-iOS/Presentation/Cells/Artist/PopularityCollectionViewCell.swift
  Spotify-iOS/Spotify-iOS/Presentation/TabBar/SpotifyTabBarController.swift
  Spotify-iOS/Spotify-iOS/Presentation/ViewControllers/Artist/ArtistMusicViewController.swift
  Spotify-iOS/Spotify-iOS/Presentation/ViewControllers/Artist/ArtistPopularityChartViewController.swift
  Spotify-iOS/Spotify-iOS/Presentation/ViewControllers/Artist/ArtistViewController.swift
  Spotify-iOS/Spotify-iOS/Presentation/ViewControllers/Home/HomeViewController.swift
  Spotify-iOS/Spotify-iOS/Presentation/ViewControllers/Recommand/MusicRecommendViewController.swift
  Spotify-iOS/Spotify-iOS/Presentation/Views/Artist/ArtistMusicView.swift
  Spotify-iOS/Spotify-iOS/Presentation/Views/Artist/ArtistView.swift
  Spotify-iOS/Spotify-iOS/Presentation/Views/Blur/BlurView.swift
Labels: 나연, Feat 🍀
